name: trabalhopos2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  image_picker: ^1.1.2  
  http: ^1.2.1
  tmbpk:
    git:
      url: https://github.com/rejanerp/TMB_PKG.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#fcefb4"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
